TODO: React Hocks 
-- State variable:- Its super power full variable, to create super power variable React introduce Hocks;
-- Hocks:- Its a normal java script utility function. there are two hocks.
-- 1: useState(): Its create superpowerfull variable. When ever a State variable update React rerender the components.
-- 2: useEffect()
-- # React uses Reconciliation Algorithm its also know as (React fiber)
-- Virtual DOM:- Its a represantaion of actual DOM, virtual dom is react DOM, whic retun Object
-- Why react is fast? Its beacuase its doing effeciant dom manupulation, Its has vertual dom, It has div algoritham, it has eficiant dom manupulation.

FIXME: 